### ISSUE TITLE
Sorry to PM through this

### ISSUE THREAD

**Issue by moronmon** [iaoiui/Selfie#1]
Hello @iaoiui, sorry to PM through this repo. I have questions, that not related to this repo.
I read your article in https://qiita.com/iaoiui/items/ee642b8b30670b21ad7c about Kubernetes event exporter using ms. teams.
I am on testing stage the Kubernetes event exporter for alert of our Kubernetes cluster, and also we use Ms. Teams for the webhook.
We have issues with the Kubernetes event exporter notification. It looks not pretty and looks messy. I try put the layout in the receivers configuration, but It doesn't work.
Here's our configuration:
```
config.yaml: |
    logLevel: debug
    logFormat: json
    route:
      routes:
        - match:
          - kind: "Pod|Deployment|ReplicaSet|StatefulSet"
            namespace: "staging|monitoring|production"
            reason: "Failed*|Started*|Successful*"
            receiver: "ms_teams"
   receivers:
     - name: "ms_teams"
        teams:
          endpoint: "https://outlook.office.com/webhook/.../"
          layout:
            eventType: "p-bbox-k8s-event"
            createdAt: "{{ .getTimestampMs }}"
            details:
              message: "{{ .message }}"
              reason: "{{ .Reason }}"
              tip: "{{ .Type }}"
              count: "{{ .Count }}"
              kind: "{{ .InvolvedObject.Kind }}"
              name: "{{ .InvolvedObject.Name }}"
              namespace: "{{ .Namespace }}"
              component: "{{ .Source.Component }}"
              host: "{{ .Source.Host }}"
              labels: "{{ toJson .InvolvedObject.Labels}}"
```
Is there any way to make the notification more easy to read in Ms. Teams webhook?
